<p>Para que seja possível realizar a instalação, alterações de código, e uso do aplicativo, é preciso concordar com o termos de 
licenciamento abaixo.</p>

<p>Caso esteja em desacordo com tais termos, aborte a instalação agora. A instalação e execução do código deste aplicativo por quaisquer meios que sejam implica na imediata aceitação dos termos de licença expostos abaixo.

<?php echo $this->form;?>