<p>Bem vindo aos serviços de dados de apoio de interfaces do SanSIS.
<p>Os seguintes serviços estão disponíveis aqui exclusivamente para as páginas do SanSIS:
<ul>
	<li><a href="<?php echo $this->baseUrl('/index.php/webservices/supportdata/uf/');?>">Lista de UFs por País</a></li>
	<li><a href="<?php echo $this->baseUrl('/index.php/webservices/supportdata/cidade/');?>">Lista de Cidades por UF</a></li>
</ul>
<p>Todos os serviços são bloqueados para uso exclusivo do SanSIS. Toda e qualquer tentativa de uso indevido é registrada. Por favor, não insista.